development:
  database: tracking_service_plattaform_development
  adapter:  mysql2
  encoding: utf8
  pool:     5
  username: cuni
  password: #PASSWORD#
  host:    localhost

test:
  database: tracking_service_plattaform_test
  adapter:  mysql2
  encoding: utf8
  pool:     5
  username: cuni
  password: #PASSWORD#
  host:    localhost

production:
  host: <%= ENV["DATABASE_HOST"] %>
